#!/usr/bin/env bash
# ~/dotfiles/ai/install.sh
#
# Creates symlinks so the agent skills in ~/dotfiles/ai/.agents/skills/
# are discovered by all supported AI agentic tools.
#
# Supported tools:
#   - Agent Skills standard (~/.agents/skills/)
#   - Claude Code           (~/.claude/skills/)
#   - Cursor                (~/.cursor/rules/ — adapted .mdc file)
#   - OpenAI Codex CLI      (~/.codex/instructions/)
#   - GitHub Copilot        (project-level only; see notes below)
#
# Usage:
#   bash ~/dotfiles/ai/install.sh

set -euo pipefail

SKILLS_SRC="$HOME/dotFiles/ai/.agents/skills"
ANTHROPIC_SKILLS_SRC="$HOME/dotFiles/ai/anthropic-skills/skills"
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

info() { echo -e "  ${BLUE}→${RESET} $*"; }
success() { echo -e "  ${GREEN}✓${RESET} $*"; }
warn() { echo -e "  ${YELLOW}!${RESET} $*"; }
header() { echo -e "\n${BOLD}$*${RESET}"; }

# ── Helpers ───────────────────────────────────────────────────────────────────

# Create a symlink, replacing an existing one. Backs up a plain file.
make_symlink() {
  local target="$1"
  local link="$2"
  local link_dir
  link_dir="$(dirname "$link")"
  mkdir -p "$link_dir"

  if [ -L "$link" ]; then
    rm "$link"
  elif [ -e "$link" ]; then
    warn "$link exists (not a symlink) — backing up to ${link}.bak"
    mv "$link" "${link}.bak"
  fi

  ln -s "$target" "$link"
  success "$(basename "$link") → $target"
}

# ── 1. Agent Skills standard path (~/.agents/skills/) ────────────────────────
header "Agent Skills (standard — ~/.agents/skills/)"
info "Symlinking each skill directory..."

mkdir -p "$HOME/.agents/skills"
for skill_dir in "$SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  make_symlink "$skill_dir" "$HOME/.agents/skills/$skill_name"
done

for skill_dir in "$ANTHROPIC_SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  make_symlink "$skill_dir" "$HOME/.agents/skills/$skill_name"
done

# ── 2. Claude Code (~/.claude/skills/) ───────────────────────────────────────
header "Claude Code (~/.claude/skills/)"
info "Claude Code reads skills from ~/.claude/skills/<name>/SKILL.md"

mkdir -p "$HOME/.claude/skills"
for skill_dir in "$SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  make_symlink "$skill_dir" "$HOME/.claude/skills/$skill_name"
done

for skill_dir in "$ANTHROPIC_SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  make_symlink "$skill_dir" "$HOME/.claude/skills/$skill_name"
done

# ── 3. Cursor (~/.cursor/rules/) ─────────────────────────────────────────────
# Cursor uses .mdc (Markdown with YAML frontmatter) rules, not the Agent Skills
# directory format. We generate a .mdc wrapper that embeds the SKILL.md content
# so Cursor can apply it as a global rule.
header "Cursor (~/.cursor/rules/)"
info "Cursor uses .mdc rule files. Generating wrappers from SKILL.md content..."

mkdir -p "$HOME/.cursor/rules"
for skill_dir in "$SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  skill_md="$skill_dir/SKILL.md"
  if [ ! -f "$skill_md" ]; then
    warn "No SKILL.md found in $skill_dir — skipping Cursor rule"
    continue
  fi

  cursor_rule="$HOME/.cursor/rules/${skill_name}.mdc"
  # Extract description from frontmatter (first description: line)
  description="$(grep -m1 '^description:' "$skill_md" | sed 's/^description: *//' | head -c 256 || echo "$skill_name")"

  # Write .mdc wrapper — embeds full SKILL.md as the rule body.
  # alwaysApply: false means Cursor uses it as an on-demand rule.
  {
    echo "---"
    echo "description: ${description}"
    echo "globs:"
    echo "alwaysApply: false"
    echo "---"
    echo ""
    echo "<!-- Source: $skill_md -->"
    echo "<!-- This file is auto-generated by ~/dotfiles/ai/install.sh -->"
    echo "<!-- Edit the source SKILL.md and re-run install.sh to update. -->"
    echo ""
    # Skip the YAML frontmatter block when embedding
    awk '/^---/{if(NR==1){in_front=1; next} if(in_front){in_front=0; next}} !in_front' "$skill_md"
  } >"$cursor_rule"

  success "${skill_name}.mdc → $cursor_rule (from $skill_md)"
done

for skill_dir in "$ANTHROPIC_SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  skill_md="$skill_dir/SKILL.md"
  if [ ! -f "$skill_md" ]; then
    warn "No SKILL.md found in $skill_dir — skipping Cursor rule"
    continue
  fi

  cursor_rule="$HOME/.cursor/rules/${skill_name}.mdc"
  # Extract description from frontmatter (first description: line)
  description="$(grep -m1 '^description:' "$skill_md" | sed 's/^description: *//' | head -c 256 || echo "$skill_name")"

  # Write .mdc wrapper — embeds full SKILL.md as the rule body.
  # alwaysApply: false means Cursor uses it as an on-demand rule.
  {
    echo "---"
    echo "description: ${description}"
    echo "globs:"
    echo "alwaysApply: false"
    echo "---"
    echo ""
    echo "<!-- Source: $skill_md -->"
    echo "<!-- This file is auto-generated by ~/dotfiles/ai/install.sh -->"
    echo "<!-- Edit the source SKILL.md and re-run install.sh to update. -->"
    echo ""
    # Skip the YAML frontmatter block when embedding
    awk '/^---/{if(NR==1){in_front=1; next} if(in_front){in_front=0; next}} !in_front' "$skill_md"
  } >"$cursor_rule"

  success "${skill_name}.mdc → $cursor_rule (from $skill_md)"
done

# ── 4. OpenAI Codex CLI (~/.codex/instructions/) ─────────────────────────────
# The Codex CLI reads ~/.codex/instructions.md as global context, and per-repo
# AGENTS.md files. We install each skill as a named file under
# ~/.codex/instructions/ (non-standard but future-proof) and append an @-import
# reference to ~/.codex/instructions.md.
header "OpenAI Codex CLI (~/.codex/instructions/)"
info "Symlinking skill markdown files as Codex instruction fragments..."

mkdir -p "$HOME/.codex/instructions"
codex_index="$HOME/.codex/instructions.md"

for skill_dir in "$SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  skill_md="$skill_dir/SKILL.md"
  if [ ! -f "$skill_md" ]; then continue; fi

  make_symlink "$skill_md" "$HOME/.codex/instructions/${skill_name}.md"
done

for skill_dir in "$ANTHROPIC_SKILLS_SRC"/*/; do
  skill_name="$(basename "$skill_dir")"
  skill_md="$skill_dir/SKILL.md"
  if [ ! -f "$skill_md" ]; then continue; fi

  make_symlink "$skill_md" "$HOME/.codex/instructions/${skill_name}.md"
done

# Create/update the top-level instructions.md with imports
{
  echo "# Agent Instructions"
  echo ""
  echo "<!-- Auto-generated by ~/dotfiles/ai/install.sh — do not edit manually -->"
  echo ""
  for skill_dir in "$SKILLS_SRC"/*/; do
    skill_name="$(basename "$skill_dir")"
    echo "@instructions/${skill_name}.md"
  done
} >"$codex_index"

{
  echo "# Agent Instructions"
  echo ""
  echo "<!-- Auto-generated by ~/dotfiles/ai/install.sh — do not edit manually -->"
  echo ""
  for skill_dir in "$ANTHROPIC_SKILLS_SRC"/*/; do
    skill_name="$(basename "$skill_dir")"
    echo "@instructions/${skill_name}.md"
  done
} >"$codex_index"
success "Updated $codex_index with skill imports"

# ── 5. GitHub Copilot ─────────────────────────────────────────────────────────
header "GitHub Copilot"
warn "GitHub Copilot CLI does not currently support a user-level skills directory."
warn "To use these skills in a Copilot-enabled project, copy or symlink the skill"
warn "directory into the project's .github/skills/ directory, e.g.:"
warn "  ln -s ~/dotfiles/ai/.agents/skills/nvim-plugin-development \\"
warn "        /path/to/project/.github/skills/nvim-plugin-development"
warn ""
warn "For Copilot workspace instructions, add a COPILOT_INSTRUCTIONS.md or"
warn "include skill content in the repository's .github/copilot-instructions.md file."

# ── Summary ───────────────────────────────────────────────────────────────────
header "Done"
echo ""
echo "  Skills source: $SKILLS_SRC"
echo "  Symlinked to:"
echo "    ~/.agents/skills/     (Agent Skills standard)"
echo "    ~/.claude/skills/     (Claude Code)"
echo "    ~/.cursor/rules/      (Cursor — .mdc wrappers generated)"
echo "    ~/.codex/instructions/ (OpenAI Codex CLI)"
echo ""
echo "  To add a new skill:"
echo "    1. Create ~/dotfiles/ai/.agents/skills/<skill-name>/SKILL.md"
echo "    2. Re-run: bash ~/dotfiles/ai/install.sh"
