//go:build ignore

// Regenerates tui/modules_register.go from modules/*/module.go.
// Usage (from repo root): go run ./tui/tools/genregister.go
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	// Allow running from tui/
	if filepath.Base(root) == "tui" {
		root = filepath.Dir(root)
	}
	modulesDir := filepath.Join(root, "modules")
	entries, err := os.ReadDir(modulesDir)
	if err != nil {
		panic(err)
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(modulesDir, e.Name(), "module.go")); err == nil {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by go run ./tui/tools/genregister.go — DO NOT EDIT.\n")
	b.WriteString("// Blank-imports every modules/<name> package so init() registers metadata.\n")
	b.WriteString("package main\n\nimport (\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t_ \"github.com/issafalcon/dotfiles-tui/modules/%s\"\n", n)
	}
	b.WriteString(")\n")

	out := filepath.Join(root, "tui", "modules_register.go")
	if err := os.WriteFile(out, []byte(b.String()), 0644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s (%d modules)\n", out, len(names))
}
